language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit

notifications:
email:
  recipients:
    - jere.marchand@gmail.com
  on_success: always
  on_failure: always