language: php
php:
- 7.1
before_script:
- composer self-update
- composer install --no-interaction
- cp .env.example .env
- php artisan key:generate
script:
- vendor/bin/phpunit
notifications: 
email:
  recipients:
  - jere.marchand@gmail.com
  on_success: always
  on_failure: always
#deploy:
#  provider: heroku
#  api_key:
#    secure: ioVjK7k78DkVM0aBzULqAooZrpLVM5dACzI5SkdyuQVJPzOg32jbyd8q2VIPxUP4TuV82oNIxugV7jlOQjODAM5iPEO0CSb7AwpDcsDO8NBrtrX6T5fVQpAgUaIWSg0zvbzWmK1qKKhEyoQvcBa8vdDt88O64lWZeaIe0NDcTKLmYboXkUduz3tjiW0rGQfsjsVOtrFAvcEiDsxfTebdVJz/jDOXOiF5H3QjxLKX7qKWzv75DKfQhKzICfWV5aqjdvrD9wopTqu1Llk3B7MFtqmPFjguWDkTFu8lCTIugxhQMR25Yi78DlQizQxI4aguAX7ZZ+UaQMlKkWq2q0LUoGU0LL4txom40Jd+uwdMxhArOSIaQheydr1u6QET61+ZEsmffVLcZCaEqlfDGoNwzWzA6CpMag8YPX2Z4nAZoHUpzlffp4l03j4jQPgGCC75tmAJKyRPxUTcJnN7zHHAwTxd/HL13UkQPWGUsz5jieQF/gi214BPYEE8vp6WzZSj08x2X9Yh1VmDG15LO93sFkNL5OstJ33QuI7EZYXQKYXM2ZYbZz+0Ouzc8HOcxbKgQdQTdvFXbXUEelLaieBxjAoQzsREGNmDquhIHQ/BynITGRCHIm3hjsgG3YY7qH4PmZ81GO5qVQZ8XkjrB4utd51pL9jgPThVqX6mcCxD3J4=
#  app: Football-Chatbot
#  on:
#    repo: Shusui95/Football-Chatbot
