language: php
php:
- 7.1
before_script:
- composer self-update
- composer install --no-interaction
- cp .env.example .env
- php artisan key:generate
script:
- vendor/bin/phpunit
notifications: 
email:
  recipients:
  - jere.marchand@gmail.com
  on_success: always
  on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: NYclMXg+Y376tVcvsj+O+lspIdGbX+A+WNuKI5k+NH9YJXJdCrnnqDG4FrChr13P+hhDh0uJxxgPaiOLm9t9PpQ43lAp80ci890H1NeX0fw8MclxY26uWlY+yZB/ENlJL3B+hsGYxUL9d02NWbOh7ZsBD2M9nQbXjbI2PCCGfGhoPSA7UYC5G3fS33Y8AatVONbb6vINE4TpO3a8Ynqhr7pHxBYBNAI+5HWHjg6WI1Zl88o/Z0cHxvztZ7cQGpUYy58pal1pFuo/UdImygV+RC3FFIirCMiHbmyy+ZoNS1aNLDmO1G7PZAKTDq5u1RYjml6sfhWQIkUbRf57ClHg/bBD/sThOdxXxyOmTuxRVf42E0n9CAQJl+40nxJPCGIisrCtpEarDf6j/FL0k8rDzQBPTJcHwWsFFF9TVMRXPAl/vVIrUn1xmaKQhrCLRv1kaNUtY7vY4gaLpXiplnFBQUdPzkum9yYBnd/YVHanNM+GgNw1O6Gqk7F7autDoiyCLldxOi5Dqy1w+bLjXEVHjO2Dr1/v8URY8o4My9XfI220haDOVp/TIQIuH+zhs+C0LVpZKwW46h4ESkKVZz2pNG012NUQvFAQ0UszcyIJiV9s4CuJTk2TOkJeNKeRn4gKqBXZRqcoTsqco3f96wxRnMV14sKBLctZCuVtgJKdUCs=
  app: Football-Chatbot
  on:
    repo: Shusui95/Football-Chatbot
